### ISSUE TITLE
Error with condition

### ISSUE THREAD

**Issue by Flaimer2** [InsinuateProjects/TrMenu#44]
**Describe the bug**
There is an error in the menu, that is, the items change by themselves

**To Reproduce**
1. Install TrMenu
2. Set this menu suffix: https://paste.helpch.at/aceweqafih.sql

**Expected behavior**
Expected that the items from the condition will not change, just so, I think there is something wrong with the priority

**Video**
https://imgur.com/a/P7i8HqA

**Additional context**

Writes an error in the console:
```
[20:47:58 WARN]: [TrMenu] Plugin TrMenu v3.0-PRE-19 generated an exception while executing task 12535
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
        at java.util.Arrays$ArrayList.get(Arrays.java:4351) ~[?:?]
        at me.arasple.mc.trmenu.util.collections.IndivList.get(IndivList.kt:22) ~[?:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.getProperty(Icon.kt:96) ~[?:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.onUpdate(Icon.kt:43) ~[?:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:26) ~[?:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:25) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$2.run(BukkitExecutor.kt:51) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
```

More:
```
[21:00:11 WARN]: [TrMenu] Plugin TrMenu v3.0-PRE-19 generated an exception while executing task 178451
java.lang.ArrayIndexOutOfBoundsException: null
```

**Server Information**
```YAML
TrMenu Dump Information (Date: 2021-08-19 19:15:31)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Paper-1618 (MC: 1.12.2) (1.12.2-R0.1-SNAPSHOT)
| Java version: 11.0.11

| TabooLib: 6.x
| TrMenu: 3.0-PRE-19
Installed Plugins:
· BetterSocial - 1.3-BETA (0 KB)
· BlockParticles - 1.12-Build#15 (0 KB)
· ConditionalEvents - 3.7.1 (0 KB)
· DisableJoinMessage - 1.0 (0 KB)
· FutureHolograms - 1.0.3 (0 KB)
· HolographicDisplays - 2.4.6 (0 KB)
· InteractiveBoard - 13.5 (0 KB)
· InteractiveBooks - 1.5.3 (0 KB)
· ItemJoin - 5.2.3-SNAPSHOT-b754 (0 KB)
· LobbyPresents - 4.3 (0 KB)
· LuckPerms - 5.2.40 (0 KB)
· MainChairs - 0.9.4 (0 KB)
· NBTAPI - 2.8.0 (0 KB)
· NoteBlockAPI - 1.6.1-SNAPSHOT (0 KB)
· PlaceholderAPI - 2.10.10 (0 KB)
· ProtocolLib - 4.5.0 (0 KB)
· RainbowBlocks - 13.0 (0 KB)
· SkinsRestorer - 14.1.3 (0 KB)
· SuperLobby - 4.3.5 (0 KB)
· TAB - 2.8.11-pre17 (0 KB)
· TrHologram - 2.2 (0 KB)
· TrMenu - 3.0-PRE-18 (0 KB)
· Vault - 1.7.1-b${env.TRAVIS_BUILD_NUMBER} (0 KB)
· XConomy - 2.27 (0 KB)
· eGlow - 3.1.0 (0 KB)
```

**Comment by 157946a** [comment]
Try to change varInt to vars to use

**Comment by Score2** [comment]
You can try @157946a's idea, I will try to fix this problem.:)

**Comment by Score2** [comment]
Fixed in latest build.:)

**Comment by Flaimer2** [comment]
The bug still happens
Menu: https://paste.helpch.at/teregoyego.sql

**Comment by Score2** [comment]
> The bug still happens
> Menu: https://paste.helpch.at/teregoyego.sql

Please provide new error information.:)

**Comment by Flaimer2** [comment]
No errors in the console

```
TrMenu Dump Information (Date: 2021-08-22 10:55:33)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Paper-1618 (MC: 1.12.2) (1.12.2-R0.1-SNAPSHOT)
| Java version: 11.0.11

| TabooLib: 6.0.0-PRE
| TrMenu: 3.0-PRE-20
Installed Plugins:
· BetterSocial - 1.3-BETA (0 KB)
· BlockParticles - 1.12-Build#15 (0 KB)
· ConditionalEvents - 3.7.1 (0 KB)
· DisableJoinMessage - 1.0 (0 KB)
· FutureHolograms - 1.0.3 (0 KB)
· HolographicDisplays - 2.4.6 (0 KB)
· InteractiveBoard - 13.5 (0 KB)
· InteractiveBooks - 1.5.3 (0 KB)
· ItemJoin - 5.2.3-SNAPSHOT-b754 (0 KB)
· LobbyPresents - 4.3 (0 KB)
· LuckPerms - 5.2.40 (0 KB)
· MainChairs - 0.9.4 (0 KB)
· NBTAPI - 2.8.0 (0 KB)
· NoteBlockAPI - 1.6.1-SNAPSHOT (0 KB)
· PlaceholderAPI - 2.10.10 (0 KB)
· ProtocolLib - 4.5.0 (0 KB)
· RainbowBlocks - 13.0 (0 KB)
· SkinsRestorer - 14.1.3 (0 KB)
· SuperLobby - 4.3.5 (0 KB)
· TAB - 2.8.11-pre17 (0 KB)
· TrHologram - 2.2 (0 KB)
· TrMenu - 3.0-PRE-20 (0 KB)
· Vault - 1.7.1-b${env.TRAVIS_BUILD_NUMBER} (0 KB)
· XConomy - 2.27 (0 KB)
· eGlow - 3.1.0 (0 KB)
```

**Comment by 157946a** [comment]
The condition format you used is wrong, and multiple conditions are required in kether instead of && but all [actions]

**Comment by Flaimer2** [comment]
> The condition format you used is wrong, and multiple conditions are required in kether instead of && but all [actions]
Like that?
```'all [ check papi *%luckperms_has_permission_suffix.alpha.1% is *yes check papi *%luckperms_has_permission_suffix.alpha.2% is *yes check papi *%luckperms_has_permission_suffix.alpha.3% is *yes check papi *%luckperms_has_permission_suffix.alpha.3% is *yes check papi *%luckperms_has_permission_suffix.alpha.4% is *yes check papi *%luckperms_has_permission_suffix.alpha.5% is *yes check papi *%luckperms_has_permission_suffix.alpha.6% is *yes check papi *%luckperms_has_permission_suffix.alpha.7% is *yes check papi *%luckperms_has_permission_suffix.alpha.8% is *yes check papi *%luckperms_has_permission_suffix.alpha.9% is *yes check papi *%luckperms_has_permission_suffix.alpha.10% is *yes check papi *%luckperms_has_permission_suffix.alpha.11% is *yes check papi *%luckperms_has_permission_suffix.alpha.12% is *yes check papi *%luckperms_has_permission_suffix.alpha.13% is *yes check papi *%luckperms_has_permission_suffix.alpha.14% is *yes check papi *%luckperms_has_permission_suffix.alpha.15% is *yes check papi *%luckperms_has_permission_suffix.alpha.16% is *yes check papi *%luckperms_has_permission_suffix.alpha.17% is *yes check papi *%luckperms_has_permission_suffix.alpha.18% is *yes check papi *%luckperms_has_permission_suffix.alpha.19% is *yes check papi *%luckperms_has_permission_suffix.alpha.20% is *yes check papi *%luckperms_has_permission_suffix.alpha.21% is *yes check papi *%luckperms_has_permission_suffix.alpha.22% is *yes check papi *%luckperms_has_permission_suffix.alpha.23% is *yes ]'```

**Comment by 157946a** [comment]
Yes that's right

**Comment by Flaimer2** [comment]
> Yes that's right

https://imgur.com/a/I5CvWY1
But the error still happens

**Comment by 157946a** [comment]
Wait a minute, I will test it myself

**Comment by 157946a** [comment]
Is there such a prompt in the background: [TrMenu] Timeout while parsing kether shell

**Comment by Flaimer2** [comment]
> Is there such a prompt in the background: [TrMenu] Timeout while parsing kether shell

No

**Comment by 157946a** [comment]
Try to use my modified version, I tested it on my computer, there was no problem, and the icon flashed once in five minutes: https://paste.helpch.at/ibezezoloy.sql

**Comment by Flaimer2** [comment]
It doesn't work...

https://imgur.com/a/1734MD3

**Comment by Flaimer2** [comment]
Oops. Wrong video.
https://imgur.com/a/XmFjGtU

**Comment by 157946a** [comment]
The problem of flashing without clicking has been solved, has it been clicked too fast and will refresh again?

**Comment by Flaimer2** [comment]
if you do not click, then a bug still occurs

> The problem of flashing without clicking has been solved, has it been clicked too fast and will refresh again?

**Comment by 157946a** [comment]
I'll test it when I come back. It may be a pot that refreshes too fast, or it may be a bug.

**Comment by 157946a** [comment]
Try to add a click delay to the Options, it is this Min-Click-Delay: 200, the unit is tick, so that the player clicks more slowly

**Comment by Neige7** [comment]
please delete all "update: 5" of your tag icon
that's what causes the flicker
in this menu, you just need "refresh 5"
"update: 5" did not work

**Comment by 157946a** [comment]
A series of your functions have been fixed. The refresh animation caused by multiple clicks can be fixed with a click delay

**Comment by Flaimer2** [comment]
> please delete all "update: 5" of your tag icon
> that's what causes the flicker
> in this menu, you just need "refresh 5"
> "update: 5" did not work

Thank you for your reply, it was helpful
